### 0. 파일 경로 지정

In [1]:
import pandas as pd
import numpy as np

from pathlib import Path
parent_path = Path.cwd().parent # 상위 폴더로 이동
file_path = parent_path/'W2_assignment'

### 1. Penguin.csv Open
penguins.csv 를 불러온 뒤 변수에 저장하고 상위 5개의 행 출력

In [2]:
df = pd.read_csv(file_path/'penguins.csv') # datafram으로 penguins.csv 불러오기
# read_csv() 를 꼭 달아줘야함

df.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female

### 2. 데이터 정보 확인
데이터프레임의 전체 행 수, 컬럼별 데이터 타입, Non-null(결측치가 아닌) 개수를 확인하는 함수를 실행하세요.

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    str
 1   island             344 non-null    str
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    str
dtypes: float64(4), str(3)
memory usage: 18.9 KB

### 3. 결측지 개수 파악
각 컬럼별로 결측치(NaN)가 총 몇 개씩 있는지 확인하세요.

In [4]:
colList = df.columns.tolist()

for i in colList:
    print(f"컬럼 {i:18}에는 {df[i].isna().sum()}개의 결측치가 있습니다.")

컬럼 species           에는 0개의 결측치가 있습니다.
컬럼 island            에는 0개의 결측치가 있습니다.
컬럼 bill_length_mm    에는 2개의 결측치가 있습니다.
컬럼 bill_depth_mm     에는 2개의 결측치가 있습니다.
컬럼 flipper_length_mm 에는 2개의 결측치가 있습니다.
컬럼 body_mass_g       에는 2개의 결측치가 있습니다.
컬럼 sex               에는 11개의 결측치가 있습니다.

### 4. 결측치 처리 (행 삭제)
결측치가 하나라도 포함된 행을 모두 제거하고, 그 결과를 df_clean이라는 새로운 변수에 저장하세요. (이후 문제는 df_clean을 사용합니다.)

In [5]:
df_copied = df.copy()
df_clean = df_copied.dropna()

# df_clean.info() 를 통해 결측치 삭제 되었는 지 확인
df_clean

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,Male
...,...,...,...,...,...,...,...
338,Gentoo,Biscoe,47.2,13.7,214.0,4925.0,Female
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

### 5. 조건 필터링 (단일 조건)
species 가 Adelie 인 펭귄 출력

In [6]:
df_clean['species'] == 'Adelie'

0       True
1       True
2       True
4       True
5       True
       ...
338    False
340    False
341    False
342    False
343    False
Name: species, Length: 333, dtype: bool

### 6. 조건 필터링 (다중 조건)

In [7]:
df_clean[ (df_clean['island'] == 'Torgersen') & (df_clean['body_mass_g'] > 4000) ]

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
7,Adelie,Torgersen,39.2,19.6,195.0,4675.0,Male
14,Adelie,Torgersen,34.6,21.1,198.0,4400.0,Male
17,Adelie,Torgersen,42.5,20.7,197.0,4500.0,Male
19,Adelie,Torgersen,46.0,21.5,194.0,4200.0,Male
69,Adelie,Torgersen,41.8,19.4,198.0,4450.0,Male
73,Adelie,Torgersen,45.8,18.9,197.0,4150.0,Male
75,Adelie,Torgersen,42.8,18.5,195.0,4250.0,Male
81,Adelie,Torgersen,42.9,17.6,196.0,4700.0,Male
83,Adelie,Torgersen,35.1,19.4,193.0,4200.0,Male
127,Adelie,Torgersen,41.5,18.3,195.0,4300.0,Male

### 7. 기술 통계 확인

In [8]:
df_clean['bill_length_mm'].describe()

count    333.000000
mean      43.992793
std        5.468668
min       32.100000
25%       39.500000
50%       44.500000
75%       48.600000
max       59.600000
Name: bill_length_mm, dtype: float64

### 8. 정렬 (Sorting)

In [9]:
df_clean['bill_length_mm'].sort_index().head(10)

0     39.1
1     39.5
2     40.3
4     36.7
5     39.3
6     38.9
7     39.2
12    41.1
13    38.6
14    34.6
Name: bill_length_mm, dtype: float64

### [!] 9. 파생 변수 생성 (Column 추가)

In [ ]:
df_clean["body_mass_kg"] = df_clean['body_mass_g'].apply(lambda x: x/1000)
# 새로 추가하는 Column =(은) body_mass_g(의 데이터를).apply(쓰다)(lambda x: x/1000)
df_clean   



# lambda는 한 줄짜리 함수라고 생각해야함. 변수: 함수. 복잡한 함수는 그냥 함수 짜라 ㅇㅇ
# apply 는 함수를 필요로 하니. 주의합시다

# for x in df_clean["body_mass_g"]:
#     df_clean["body_mass_kg"] = df_clean["body_mass_g"].apply(x)
# 이런 거는 안된대

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,body_mass_kg
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male,3.750
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female,3.800
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female,3.250
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female,3.450
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,Male,3.650
...,...,...,...,...,...,...,...,...
338,Gentoo,Biscoe,47.2,13.7,214.0,4925.0,Female,4.925
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female,4.850
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male,5.750
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female,5.200
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male,5.400

### [!] 10. 그룹화 및 집계 (GroupBy)

In [53]:
df_clean.groupby("species")
df_clean
df_clean.groupby('species')['body_mass_g'].agg(["mean"])
# df_clean.(의 데이터를)groupby(다음으로 group을 함)('species')['body_mass_g'].(의 데이터를)agg(["mean"])(으로 집계한다)
"""
df.clean 의 데이터의
.groupby 매서드인 groupby를 사용해서
('species')['body_mass_g'] 종의 g 무게를
.agg() 로 집계 하는데
['mean'] 중앙값으로 집계한다.
"""

species
Adelie       3706.164384
Chinstrap    3733.088235
Gentoo       5092.436975
Name: body_mass_g, dtype: float64

In [55]:
df_clean.groupby('species')['body_mass_g'].mean()
df_clean.groupby('species')['body_mass_g'].agg(['mean', 'count'])
# agg 안에 입력 되는 것들을 데이터프레임 형식으로 뽑아내줌
# mean은 중앙값만 짠 내주지만 agg() 는 넣는대로 보여줌
# 대괄호를 넣는 이유는, agg()가 여러 개를 받아오기 때문임

                  mean  count
species
Adelie     3706.164384    146
Chinstrap  3733.088235     68
Gentoo     5092.436975    119

In [73]:
df_clean[['island', 'species']].value_counts()
df_clean[['species', 'island']].value_counts()
# 펭귄 종까지 알아오라고 하진 않았으니까 그냥 출력하면 될듯
tempdf = df_clean['island'].value_counts()

for island, cnt in tempdf.items():
    print(f"{island:<10} 에는 {cnt:>5} 마리의 펭귄이 삽니다.")

Biscoe     에는   163 마리의 펭귄이 삽니다.
Dream      에는   123 마리의 펭귄이 삽니다.
Torgersen  에는    47 마리의 펭귄이 삽니다.

### [!] 12. 상관관계 분석 (Advanced)

In [77]:
corr_df = df_clean['flipper_length_mm'].corr(df_clean['body_mass_g'])
print(round(corr_df, 4))

corr_df = df_clean['flipper_length_mm'].corr(df_clean['body_mass_g'])
print(round(corr_df, 4))

0.873
0.873

### 데이터 다시 불러오기 (초기화)

In [78]:
df = pd.read_csv(file_path/'penguins.csv')

print(Path.cwd())

c:\Users\meeso\Desktop\Estudio\Data-Science-Deep-Dive\01_Python_Data_Analysis\Jun

### [!] 13. 결측치 대체 (Imputation)

In [79]:
df['body_mass_g'] = df["body_mass_g"].fillna(df["body_mass_g"].mean())
print(df["body_mass_g"].isna().sum())

df['body_mass_g'] = df['body_mass_g'].fillna(df['body_mass_g'].mean())

0

### 14. 고유값 확인 (Unique Values)

In [82]:
onlyList = df['species'].unique()
onlyList

<StringArray>
['Adelie', 'Chinstrap', 'Gentoo']
Length: 3, dtype: str

### 15. 행/열 선택 (loc/iloc)

In [24]:
print("-------iloc() 활용-------")
print(df.iloc[10:15])
print("-------loc() 활용-------")
print(df.loc[10:15, ['species', 'body_mass_g']])

-------iloc() 활용-------
   species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
10  Adelie  Torgersen            37.8           17.1              186.0
11  Adelie  Torgersen            37.8           17.3              180.0
12  Adelie  Torgersen            41.1           17.6              182.0
13  Adelie  Torgersen            38.6           21.2              191.0
14  Adelie  Torgersen            34.6           21.1              198.0

    body_mass_g     sex
10       3300.0     NaN
11       3700.0     NaN
12       3200.0  Female
13       3800.0    Male
14       4400.0    Male
-------loc() 활용-------
   species  body_mass_g
10  Adelie       3300.0
11  Adelie       3700.0
12  Adelie       3200.0
13  Adelie       3800.0
14  Adelie       4400.0
15  Adelie       3700.0

### [!] 16. 문자열 처리 (String Manipulation)

In [34]:
df['sex'].str.upper()

0        MALE
1      FEMALE
2      FEMALE
3         NaN
4      FEMALE
        ...
339       NaN
340    FEMALE
341      MALE
342    FEMALE
343      MALE
Name: sex, Length: 344, dtype: str

### 17. Apply에 함수 넣기

In [91]:
def checkClass(int1):
    if (int1 > 4000):
        return 'Heavy'
    else:
        return 'Light'
    

# df['mass_class'] = df['body_mass_g'].apply(checkClass)
df['mass_class'] = df['body_mass_g'].apply(lambda x: checkClass(x))

df
# p.s. 쉽네요 ㅎ 라고 할 뻔!!!!!!!!!!!!!!

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,mass_class
0,Adelie,Torgersen,39.1,18.7,181.0,3750.000000,Male,Light
1,Adelie,Torgersen,39.5,17.4,186.0,3800.000000,Female,Light
2,Adelie,Torgersen,40.3,18.0,195.0,3250.000000,Female,Light
3,Adelie,Torgersen,NaN,NaN,NaN,4201.754386,NaN,Heavy
4,Adelie,Torgersen,36.7,19.3,193.0,3450.000000,Female,Light
...,...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,4201.754386,NaN,Heavy
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.000000,Female,Heavy
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.000000,Male,Heavy
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.000000,Female,Heavy
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.000000,Male,Heavy

### 18. 피벗 테이블 ( Pivot Table )

In [99]:
df.pivot_table(values='body_mass_g', index = 'species', columns='sex', aggfunc='mean')
df.pivot_table(values='bill_length_mm', index = 'species', columns = 'sex', aggfunc = 'mean')

sex           Female       Male
species
Adelie     37.257534  40.390411
Chinstrap  46.573529  51.094118
Gentoo     45.563793  49.473770

### 19. 데이터 매핑 ( Map )

In [112]:
sex_map = {"Male":1, "Female":0}
df_clean['sex'] = df_clean['sex'].map(sex_map)
df_clean

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,body_mass_kg
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,1,3.750
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,0,3.800
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,0,3.250
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,0,3.450
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,1,3.650
...,...,...,...,...,...,...,...,...
338,Gentoo,Biscoe,47.2,13.7,214.0,4925.0,0,4.925
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,0,4.850
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,1,5.750
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,0,5.200
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,1,5.400

### 20. 데이터 샘플링 ( Sampling )

In [115]:
df_sample = df_clean.sample(10)
df_sample

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,body_mass_kg
45,Adelie,Dream,39.6,18.8,190.0,4600.0,1,4.600
89,Adelie,Dream,38.9,18.8,190.0,3600.0,0,3.600
270,Gentoo,Biscoe,46.6,14.2,210.0,4850.0,0,4.850
292,Gentoo,Biscoe,48.2,15.6,221.0,5100.0,1,5.100
119,Adelie,Torgersen,41.1,18.6,189.0,3325.0,1,3.325
331,Gentoo,Biscoe,49.8,15.9,229.0,5950.0,1,5.950
193,Chinstrap,Dream,46.2,17.5,187.0,3650.0,0,3.650
299,Gentoo,Biscoe,45.2,16.4,223.0,5950.0,1,5.950
131,Adelie,Torgersen,43.1,19.2,197.0,3500.0,1,3.500
21,Adelie,Biscoe,37.7,18.7,180.0,3600.0,1,3.600

### 21. 컬럼 이름 변경 ( Rename )

In [124]:
df_clean = df_clean.rename(columns={'bill_length_mm' : 'bill_len'})
df_clean = df_clean.rename(columns={'bill_depth_mm' : 'bill_depth'})
df_clean

,species,island,bill_len,bill_depth,flipper_length_mm,body_mass_g,sex,body_mass_kg
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,1,3.750
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,0,3.800
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,0,3.250
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,0,3.450
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,1,3.650
...,...,...,...,...,...,...,...,...
338,Gentoo,Biscoe,47.2,13.7,214.0,4925.0,0,4.925
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,0,4.850
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,1,5.750
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,0,5.200
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,1,5.400

### 22. 데이터 저장 ( To CSV )

In [125]:
df_clean.to_csv("processed_penguins.csv", index=False)