## 1. Basic

In [1]:
from pathlib import Path
parent_path = Path.cwd().parent # 절대경로의 부모 디렉토리
file_path = parent_path/"W2_assignment"

import pandas as pd
df = pd.read_csv(file_path/"penguins.csv")

사람.move() <- 매서드
사람.hands <- 피처

cwd() 현재 파일의 경로
cwd().parent 현재 파일의 경로의 부모

In [2]:
df

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

NaN = 결측값

In [3]:
df.head() # 앞에서 N개 (기본값 5)
df.tail() # 뒤에서 N개 (기본값 5)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    str
 1   island             344 non-null    str
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    str
dtypes: float64(4), str(3)
memory usage: 18.9 KB

Non-Null Count로 결측값 개수를 알 수 있음

In [5]:
df.shape

(344, 7)

In [6]:
df.columns.tolist()

['species',
 'island',
 'bill_length_mm',
 'bill_depth_mm',
 'flipper_length_mm',
 'body_mass_g',
 'sex']

In [7]:
df.describe()

       bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g
count      342.000000     342.000000         342.000000   342.000000
mean        43.921930      17.151170         200.915205  4201.754386
std          5.459584       1.974793          14.061714   801.954536
min         32.100000      13.100000         172.000000  2700.000000
25%         39.225000      15.600000         190.000000  3550.000000
50%         44.450000      17.300000         197.000000  4050.000000
75%         48.500000      18.700000         213.000000  4750.000000
max         59.600000      21.500000         231.000000  6300.000000

count: ?

mean: 중간값

std: 표준편차

25%: q1

50%: q2

75%: q3

max: q4

In [8]:
df['species'].unique()

<StringArray>
['Adelie', 'Chinstrap', 'Gentoo']
Length: 3, dtype: str

In [9]:
df['species'].value_counts()

species
Adelie       152
Gentoo       124
Chinstrap     68
Name: count, dtype: int64

In [10]:
df[['species', 'island']]
df['species'].value_counts()
df_Chinstrap = df[df['species'] == 'Chinstrap']
df_Chinstrap
df['species'] == 'Chinstrap'

df[df['species'] == 'Chinstrap']
df[ (df['species'] == 'Chinstrap') | (df['species'] == 'Adelie') ]

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
...,...,...,...,...,...,...,...
215,Chinstrap,Dream,55.8,19.8,207.0,4000.0,Male
216,Chinstrap,Dream,43.5,18.1,202.0,3400.0,Female
217,Chinstrap,Dream,49.6,18.2,193.0,3775.0,Male
218,Chinstrap,Dream,50.8,19.0,210.0,4100.0,Male
219,Chinstrap,Dream,50.2,18.7,198.0,3775.0,Female

In [11]:
df['island'].value_counts()
df[df['island'].isin(['Biscoe', 'Dream'])]

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
20,Adelie,Biscoe,37.8,18.3,174.0,3400.0,Female
21,Adelie,Biscoe,37.7,18.7,180.0,3600.0,Male
22,Adelie,Biscoe,35.9,19.2,189.0,3800.0,Female
23,Adelie,Biscoe,38.2,18.1,185.0,3950.0,Male
24,Adelie,Biscoe,38.8,17.2,180.0,3800.0,Male
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

In [12]:
df.iloc[:5, :2]

  species     island
0  Adelie  Torgersen
1  Adelie  Torgersen
2  Adelie  Torgersen
3  Adelie  Torgersen
4  Adelie  Torgersen

In [13]:
df.loc[:5, ['species', 'island']]

  species     island
0  Adelie  Torgersen
1  Adelie  Torgersen
2  Adelie  Torgersen
3  Adelie  Torgersen
4  Adelie  Torgersen
5  Adelie  Torgersen

In [14]:
df.isna().sum()

species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
dtype: int64

In [15]:
df_na = df.dropna()
df_na.info()

<class 'pandas.DataFrame'>
Index: 333 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            333 non-null    str
 1   island             333 non-null    str
 2   bill_length_mm     333 non-null    float64
 3   bill_depth_mm      333 non-null    float64
 4   flipper_length_mm  333 non-null    float64
 5   body_mass_g        333 non-null    float64
 6   sex                333 non-null    str
dtypes: float64(4), str(3)
memory usage: 20.8 KB

In [16]:
df_fill = df.copy()
df_fill['bill_length_mm'] = df_fill['bill_length_mm'].fillna(df['bill_length_mm'].mean())
df_fill['sex'] = df_fill['sex'].fillna(df_fill['sex'].mode().iloc[0])
# mode()는 N 이라는 게 3번 나왔습니다 (N, 3) 튜플로
df_fill = df_fill.dropna()
df_fill.info()

<class 'pandas.DataFrame'>
Index: 342 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            342 non-null    str
 1   island             342 non-null    str
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                342 non-null    str
dtypes: float64(4), str(3)
memory usage: 21.4 KB

In [17]:
df_temp = df.copy()
df_temp = df_temp.drop(['flipper_length_mm', 'sex'], axis=1)
df_temp.head()

  species     island  bill_length_mm  bill_depth_mm  body_mass_g
0  Adelie  Torgersen            39.1           18.7       3750.0
1  Adelie  Torgersen            39.5           17.4       3800.0
2  Adelie  Torgersen            40.3           18.0       3250.0
3  Adelie  Torgersen             NaN            NaN          NaN
4  Adelie  Torgersen            36.7           19.3       3450.0

In [18]:
df['bill_length_mm'].sort_values()
df.sort_values(by='bill_length_mm', ascending=False)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
253,Gentoo,Biscoe,59.6,17.0,230.0,6050.0,Male
169,Chinstrap,Dream,58.0,17.8,181.0,3700.0,Female
321,Gentoo,Biscoe,55.9,17.0,228.0,5600.0,Male
215,Chinstrap,Dream,55.8,19.8,207.0,4000.0,Male
335,Gentoo,Biscoe,55.1,16.0,230.0,5850.0,Male
...,...,...,...,...,...,...,...
70,Adelie,Torgersen,33.5,19.0,190.0,3600.0,Female
98,Adelie,Dream,33.1,16.1,178.0,2900.0,Female
142,Adelie,Dream,32.1,15.5,188.0,3050.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN

In [21]:
df['bill_length_cm'] = df['bill_length_mm'].apply(lambda x: x/10)
df

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,bill_length_cm
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male,3.91
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female,3.95
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female,4.03
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female,3.67
...,...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female,4.68
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male,5.04
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female,4.52
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male,4.99

In [25]:
df.groupby('species')['body_mass_g'].agg(['mean', 'min', 'max', 'std'])
df.describe()

,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,bill_length_cm
count,342.000000,342.000000,342.000000,342.000000,342.000000
mean,43.921930,17.151170,200.915205,4201.754386,4.392193
std,5.459584,1.974793,14.061714,801.954536,0.545958
min,32.100000,13.100000,172.000000,2700.000000,3.210000
25%,39.225000,15.600000,190.000000,3550.000000,3.922500
50%,44.450000,17.300000,197.000000,4050.000000,4.445000
75%,48.500000,18.700000,213.000000,4750.000000,4.850000
max,59.600000,21.500000,231.000000,6300.000000,5.960000