# Pandas

## 0. Pandas 라이브러리의 기능

고수준의 자료구조 (Series, DataFrame)과 빠르고 쉬운 데이터 분석 도구 제공
넘파이, 사이파이, statsmodels, sklearn, matplotlib과 함께 사용하면 good

In [1]:
# import 컨벤션
import pandas as pd
import numpy as np

from pandas import Series, DataFrame # 로컬 네임스페이스로 불러오는게 더 편함

## 1. 자료구조

### 1.1. Series

왼쪽에는 index 오른쪽에는 해당 index의 값 출력

In [2]:
obj = pd.Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [3]:
# 배열과 색인 객체
print(obj.array)
print(obj.index)

<NumpyExtensionArray>
[np.int64(4), np.int64(7), np.int64(-5), np.int64(3)]
Length: 4, dtype: int64
RangeIndex(start=0, stop=4, step=1)

In [4]:
obj2 = pd.Series([4, 7, -5, 3], index=["d", "b", "a", "c"]) # index 지정
obj2["a"]

np.int64(-5)

In [5]:
obj2["d"] = 6 # 색인으로 접근
obj2[["a", "b", "d"]] # 색인의 배열으로 접근

a   -5
b    7
d    6
dtype: int64

In [6]:
obj2[obj2 < 0]

a   -5
dtype: int64

In [7]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [8]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [9]:
dict_data = {'A':1, 'B':2, 'C':3, 'D':4}
obj3 = pd.Series(dict_data)
obj3

A    1
B    2
C    3
D    4
dtype: int64

In [10]:
obj3.to_dict()

{'A': 1, 'B': 2, 'C': 3, 'D': 4}

In [11]:
index = ['B', 'C', 'D', 'E']
obj4=pd.Series(dict_data, index=index) # 인덱스대로 정렬
obj4

B    2.0
C    3.0
D    4.0
E    NaN
dtype: float64

In [12]:
print(obj4.isna())
print(obj4.notna())

B    False
C    False
D    False
E     True
dtype: bool
B     True
C     True
D     True
E    False
dtype: bool

In [13]:
obj3 + obj4

A    NaN
B    4.0
C    6.0
D    8.0
E    NaN
dtype: float64

In [14]:
obj3.name = "nums" # Series 객체와 색인은 이름을 가진다.
obj3.index.name = "state"
print(obj3)

state
A    1
B    2
C    3
D    4
Name: nums, dtype: int64

In [15]:
obj.index = ["A", "B", "C", "D"] # 대입으로 인덱스를 변경할 수 있다.
obj

A    4
B    7
C   -5
D    3
dtype: int64

## 1.2. DataFrame

In [16]:
data = {"state":["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
        "year":[2001,2002,2003,2004,2005,2006],
        "pop":[1.5,1.7,3.6,2.4,2.9,3.2]}
frame = pd.DataFrame(data)
frame

    state  year  pop
0    Ohio  2001  1.5
1    Ohio  2002  1.7
2    Ohio  2003  3.6
3  Nevada  2004  2.4
4  Nevada  2005  2.9
5  Nevada  2006  3.2

In [17]:
frame.head()

    state  year  pop
0    Ohio  2001  1.5
1    Ohio  2002  1.7
2    Ohio  2003  3.6
3  Nevada  2004  2.4
4  Nevada  2005  2.9

In [18]:
pd.DataFrame(data, columns=["year","state"]) # 원하는 순서대로, 원하는 열만 지정

   year   state
0  2001    Ohio
1  2002    Ohio
2  2003    Ohio
3  2004  Nevada
4  2005  Nevada
5  2006  Nevada

In [19]:
frame2 = pd.DataFrame(data, columns=["year","state","pop","debt"]) # 딕셔너리에 없는 값은 Na
frame2

   year   state  pop debt
0  2001    Ohio  1.5  NaN
1  2002    Ohio  1.7  NaN
2  2003    Ohio  3.6  NaN
3  2004  Nevada  2.4  NaN
4  2005  Nevada  2.9  NaN
5  2006  Nevada  3.2  NaN

In [20]:
frame2["state"]

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: object

In [21]:
frame2.loc[1]

year     2002
state    Ohio
pop       1.7
debt      NaN
Name: 1, dtype: object

In [22]:
frame2.iloc[2]

year     2003
state    Ohio
pop       3.6
debt      NaN
Name: 2, dtype: object

In [23]:
frame2["debt"] = np.arange(6.) # 대입으로 열 전체 수정
frame2

   year   state  pop  debt
0  2001    Ohio  1.5   0.0
1  2002    Ohio  1.7   1.0
2  2003    Ohio  3.6   2.0
3  2004  Nevada  2.4   3.0
4  2005  Nevada  2.9   4.0
5  2006  Nevada  3.2   5.0

In [24]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
frame2['debt'] = val # 색인에 따라 값이 대입. 존재하지 않으면 결측치가 대입된다
frame2

   year   state  pop  debt
0  2001    Ohio  1.5   NaN
1  2002    Ohio  1.7   NaN
2  2003    Ohio  3.6   NaN
3  2004  Nevada  2.4   NaN
4  2005  Nevada  2.9   NaN
5  2006  Nevada  3.2   NaN

In [25]:
frame2["isohio"] = (frame2["state"] == "Ohio") # 불리언 열 추가
frame2

   year   state  pop  debt  isohio
0  2001    Ohio  1.5   NaN    True
1  2002    Ohio  1.7   NaN    True
2  2003    Ohio  3.6   NaN    True
3  2004  Nevada  2.4   NaN   False
4  2005  Nevada  2.9   NaN   False
5  2006  Nevada  3.2   NaN   False

In [26]:
del frame2["isohio"] # 열 삭제
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [27]:
# 중첩된 딕셔너리
population = {"ohio": {2000: 1.5, 2001:1.7, 2002:3.6},
              "Nevada": {2001:2.4, 2002:2.9}}
frame3 = pd.DataFrame(population)
frame3

      ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [28]:
frame3.T

        2000  2001  2002
ohio     1.5   1.7   3.6
Nevada   NaN   2.4   2.9

In [29]:
pd.DataFrame(population, index=[2001,2002,2003])

      ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9
2003   NaN     NaN

In [30]:
frame3.index.name = "year"
frame3.columns.name = "state"
print(frame3)

state  ohio  Nevada
year
2000    1.5     NaN
2001    1.7     2.4
2002    3.6     2.9

In [31]:
frame3.to_numpy()

array([[1.5, nan],
       [1.7, 2.4],
       [3.6, 2.9]])

### 1.3. 색인 객체

In [ ]:
obj = pd.Series(np.arange(3), index=['a','b','c'])
index = obj.index
index[1:] # pd.Index 자료형

Index(['b', 'c'], dtype='object')

In [34]:
index[1] = 'd' # 색인 객체는 변경이 불가능하다

TypeError: Index does not support mutable operations

In [35]:
labels = pd.Index(np.arange(3))
labels

Index([0, 1, 2], dtype='int64')

In [36]:
obj2 = pd.Series([1.5, -2.5, 0.], index=labels)
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [37]:
frame3

state  ohio  Nevada
year
2000    1.5     NaN
2001    1.7     2.4
2002    3.6     2.9

In [38]:
frame3.columns

Index(['ohio', 'Nevada'], dtype='object', name='state')

In [39]:
'ohio' in frame3.columns

True

In [40]:
# 중복되는 값을 허용한다
pd.Index(['a','a','b','b'])

Index(['a', 'a', 'b', 'b'], dtype='object')

In [58]:
# 색인 메서드와 속성
index = pd.Index(['a','b','c','d'])
index = index.append(pd.Index(['e'])) # a b c d e
index = index.difference(pd.Index(['e'])) # a b c d  차집합/ intersection 교집합/ union 합집합
index.isin(['a']) # True False False False 배열
index = index.delete(3) # 3번째 인덱스 d 제거
index = index.insert(3, 'd') # d 추가
index = index.drop('d')
index.is_unique # 중복 있으면 False
index.unique() # 중복 제거. 유일한 값만 반환

Index(['a', 'b', 'c'], dtype='object')

## 2. 핵심 기능

### 2.1. 재색인 reindex

In [59]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d','b','a','c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [61]:
obj2 = obj.reindex(["a", "b", "c", "d", "e"]) # 새로운 색인에 맞게 재배열, 없는 값은 결측치
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [64]:
obj3 = pd.Series(["blue", "purple", "yellow"], index=[0,2,4])
obj3 = obj3.reindex(np.arange(6), method='ffill')
obj3

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [66]:
frame = pd.DataFrame(np.arange(9).reshape((3,3)),
                     index=["a", "c", "d"],
                     columns=["Ohio", "Texas", "California"])
frame

   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [67]:
frame2 = frame.reindex(index=["a","b","c","d"])
frame2

   Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [68]:
frame.reindex(columns=["Texas", "Utah", "California"])

   Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [70]:
obj = pd.Series(np.arange(5.), index=['a','b','c','d','e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [73]:
new_obj = obj.drop(['c', 'd', 'e'])
new_obj

a    0.0
b    1.0
dtype: float64

In [74]:
data = pd.DataFrame(np.arange(16).reshape((4,4)), index=["Ohio", "Colorado", "Utah", "New York"],
                    columns=["one", "two", "three", "four"])
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [76]:
data.drop(index=["Colorado", "Ohio"]) # 인수로 index 이름을 넘기면 행 삭제

          one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [78]:
data.drop(["two"], axis=1) # 열 삭제는 columns=삭제할 행 또는 axis=1 인수

          one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

### 2.3. 색인하기, 선택하기, 거르기

In [79]:
obj = pd.Series(np.arange(4.), index=["a","b","c","d"])

In [81]:
# 넘파이와 유사하지만 loc과 iloc사용을 더 선호한다. []로 선택하면 색인의 자료형에 따라 작동 방식이 달라지기 때문이다
obj.loc[["b","a","d"]]

b    1.0
a    0.0
d    3.0
dtype: float64

In [82]:
# iloc 연산자는 int loc. 즉 정수로만 일관되게 작동한다
obj.iloc[[0,1,2]]

a    0.0
b    1.0
c    2.0
dtype: float64

In [83]:
data = pd.DataFrame(np.arange(16).reshape((4,4)), index=["Ohio", "Colorado", "Utah", "New York"],
                    columns=["one", "two", "three", "four"])

In [85]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [86]:
data[['one','two']]

          one  two
Ohio        0    1
Colorado    4    5
Utah        8    9
New York   12   13

In [87]:
# 슬라이싱으로 행 선택 가능
data[:2]

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [ ]:
data < 5 # 스칼라 비교

            one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [89]:
data[data<5] = 0
data

          one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [91]:
data.loc[["Colorado", "New York"]]

          one  two  three  four
Colorado    0    5      6     7
New York   12   13     14    15

In [94]:
data.loc[["Colorado", "New York"], ["two", "three"]] # 쉼표로 행, 열 조합해 선택

          two  three
Colorado    5      6
New York   13     14

In [97]:
data.iloc[[1,2]]

          one  two  three  four
Colorado    0    5      6     7
Utah        8    9     10    11

In [99]:
# 인덱스가 다른 배열의 연산. 서로 없는 값은 결측치로 바꿈/ DataFrame의 경우는 행과 열에 모두 결측치
a = pd.Series(np.arange(3), index=['a','b','c'])
b = pd.Series(np.arange(4), index=['a','b','d','e'])
a+b

a    0.0
b    2.0
c    NaN
d    NaN
e    NaN
dtype: float64

In [102]:
df1 = pd.DataFrame({"A":[1,2]})
df2 = pd.DataFrame({"b":[3,4]})
df1.add(df2, fill_value=0) # 이렇게 하면 없는 값을 0으로 해서 결측치로 변하는거 방지함 add, sub, div, mul, pow, floordiv(소수점 내림 연산 //)
                                                                                    # radd, rsub, rdiv ..... 뒤집어서 계산 1/df == df.rdiv(1)

     A    b
0  1.0  3.0
1  2.0  4.0

In [105]:
arr = np.arange(12.).reshape((3,4))
arr - arr[0] # 각 행에 대해서 한 번씩 수행 (브로드캐스팅)

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [120]:
# DataFrame도 유사함
frame = pd.DataFrame(np.arange(12.).reshape((4,3)),
                     columns=['b','d','e'],
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [121]:
series = frame.iloc[0]
frame - series # 아래 행으로 브로드캐스팅

          b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [ ]:
series2 = frame['d']

frame.sub(series2, axis=0) # 각 행에 대해 연산 수행

          b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

### 2.5 함수 적용과 매핑

In [129]:
frame = pd.DataFrame(np.random.standard_normal((4,3)),
                     columns=['b','d','e'],
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

               b         d         e
Utah   -0.917483 -1.152544 -2.692969
Ohio    0.892035 -0.411307 -0.521211
Texas   0.177549 -0.408933  1.208355
Oregon  0.371209  1.279474  1.187668

In [130]:
np.abs(frame)

               b         d         e
Utah    0.917483  1.152544  2.692969
Ohio    0.892035  0.411307  0.521211
Texas   0.177549  0.408933  1.208355
Oregon  0.371209  1.279474  1.187668

In [131]:
def f1(x):
    return x.max() - x.min()

frame.apply(f1)

b    1.809518
d    2.432018
e    3.901323
dtype: float64

In [133]:
frame.apply(f1, axis='columns') # 각 행에 대해서 한 번씩만 수행

Utah      1.775485
Ohio      1.413246
Texas     1.617288
Oregon    0.908266
dtype: float64

In [134]:
def f2(x):
    return pd.Series([x.min(), x.max()], index=['min','max'])
frame.apply(f2)

            b         d         e
min -0.917483 -1.152544 -2.692969
max  0.892035  1.279474  1.208355

In [135]:
def my_format(x):
    return f"{x:.2f}"
frame.applymap(my_format)

C:\Users\devsa\AppData\Local\Temp\ipykernel_26280\1380983260.py:3: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  frame.applymap(my_format)

            b      d      e
Utah    -0.92  -1.15  -2.69
Ohio     0.89  -0.41  -0.52
Texas    0.18  -0.41   1.21
Oregon   0.37   1.28   1.19

### 2.6. 정렬과 순위

In [137]:
obj = pd.Series(np.arange(4), index=["d","a","b","c"])
obj.sort_index() # 알파벳순 오름차순

a    1
b    2
c    3
d    0
dtype: int64

In [138]:
frame = pd.DataFrame(np.arange(8).reshape((2,4)),
                     index=["three", "one"],
                     columns=['d','a','c','b'])
frame

       d  a  c  b
three  0  1  2  3
one    4  5  6  7

In [144]:
frame.sort_index(axis='columns')

       a  b  c  d
three  1  3  2  0
one    5  7  6  4

In [145]:
frame.sort_index(axis=1, ascending=False)

       d  c  b  a
three  0  2  3  1
one    4  6  7  5

In [149]:
frame = pd.DataFrame({"b":[4,7,-3,2], "a":[0,1,0,1]})
frame.sort_values(["b"]) # b열을 기준으로 정렬

   b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [152]:
frame.sort_values(["a","b"])

   b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [ ]:
obj = pd.Series([7,-5,7,4,2,0,4])
obj.rank() #

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [156]:
frame = pd.DataFrame({'b':[4.3, 7, -3, 2], "a":[0,1,0,1], "c":[-2,5,8,-2.5]})
frame

     b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [157]:
frame.rank()

     b    a    c
0  3.0  1.5  2.0
1  4.0  3.5  3.0
2  1.0  1.5  4.0
3  2.0  3.5  1.0

In [161]:
frame.rank(axis=1) # method= 'average', 'min', 'max', 'first', 'dense'

     b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

In [163]:
obj = pd.Series(np.arange(5), index=['a', 'a', 'b', 'b', 'c'])
obj.index.is_unique

False

In [164]:
obj['a']

a    0
a    1
dtype: int64

In [166]:
df = pd.DataFrame(np.random.standard_normal((5,3)), index=['a','a','b','b', 'c'])
df

          0         1         2
a  0.695265 -0.382027 -0.664733
a -1.607903  1.058646 -0.327524
b -1.921952 -1.079856  0.996998
b  1.046738  0.097915 -0.102060
c -0.457150 -1.413967 -1.746852

In [167]:
df.loc['b']

          0         1         2
b -1.921952 -1.079856  0.996998
b  1.046738  0.097915 -0.102060

## 3. 기술 통계 계산과 요약

In [169]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5], [np.nan,np.nan], [0.75, -1.3]],
                  index=['a','b','c','d'],
                  columns=['one','two'])
df

    one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [170]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [171]:
df.sum(axis=1)

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [175]:
df.sum(axis=1,skipna=True)

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [176]:
df.cumsum()

    one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [178]:
df.describe()

            one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

여러 메서드
count, describe, min, max, argmin, argmax, idxmin, idxmax, quantile, sum, mean, median, mad, prod, var, std, skew, kurt, cumsum, cummin, cummax, cumprod, diff, pct_change

### 3.1. 상관관계, 공분산

In [180]:
price = pd.read_pickle("yahoo_price.pkl")
volume = pd.read_pickle("yahoo_volume.pkl")

In [183]:
returns = price.pct_change()
returns.tail()

                AAPL      GOOG       IBM      MSFT
Date
2016-10-17 -0.000680  0.001837  0.002072 -0.003483
2016-10-18 -0.000681  0.019616 -0.026168  0.007690
2016-10-19 -0.002979  0.007846  0.003583 -0.002255
2016-10-20 -0.000512 -0.005652  0.001719 -0.004867
2016-10-21 -0.003930  0.003011 -0.012474  0.042096

In [185]:
returns["MSFT"].corr(returns["IBM"])

np.float64(0.4997636114415114)

In [186]:
returns["MSFT"].cov(returns["IBM"])

np.float64(8.870655479703546e-05)

In [187]:
returns.corr()

          AAPL      GOOG       IBM      MSFT
AAPL  1.000000  0.407919  0.386817  0.389695
GOOG  0.407919  1.000000  0.405099  0.465919
IBM   0.386817  0.405099  1.000000  0.499764
MSFT  0.389695  0.465919  0.499764  1.000000

In [188]:
returns.corrwith(returns["IBM"])

AAPL    0.386817
GOOG    0.405099
IBM     1.000000
MSFT    0.499764
dtype: float64

In [189]:
returns.corrwith(volume)

AAPL   -0.075565
GOOG   -0.007067
IBM    -0.204849
MSFT   -0.092950
dtype: float64

### 3.2. 유일값, 값 세기, 멤버십

In [ ]:
obj = pd.Series(['c', 'a','d','a','a','b','b','c','c'])
uniques = obj.unique() # 유일값만 담은 Series
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [192]:
obj.value_counts()

c    3
a    3
b    2
d    1
Name: count, dtype: int64

In [193]:
pd.value_counts(obj.to_numpy(), sort=False)

C:\Users\devsa\AppData\Local\Temp\ipykernel_26280\164454357.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(obj.to_numpy(), sort=False)

c    3
a    3
d    1
b    2
Name: count, dtype: int64

In [196]:
mask = obj.isin(['b','c'])
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [197]:
data = pd.DataFrame({"Qu1": [1,3,4,3,4],
                     "Qu2": [2,3,1,2,3],
                     "Qu3": [1,5,2,4,4]})
data

   Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [198]:
data["Qu1"].value_counts().sort_index()

Qu1
1    1
3    2
4    2
Name: count, dtype: int64

In [199]:
result = data.apply(pd.value_counts).fillna(0)
result

C:\Users\devsa\AppData\Local\Temp\ipykernel_26280\1382616601.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  result = data.apply(pd.value_counts).fillna(0)

   Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0