# Pandas

## 0. Pandas 라이브러리의 기능

고수준의 자료구조 (Series, DataFrame)과 빠르고 쉬운 데이터 분석 도구 제공
넘파이, 사이파이, statsmodels, sklearn, matplotlib과 함께 사용하면 good

In [3]:
# import 컨벤션
import pandas as pd
import numpy as np

from pandas import Series, DataFrame # 로컬 네임스페이스로 불러오는게 더 편함

## 1. 자료구조

### 1.1. Series

왼쪽에는 index 오른쪽에는 해당 index의 값 출력

In [9]:
obj = pd.Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [13]:
# 배열과 색인 객체
print(obj.array)
print(obj.index)

<NumpyExtensionArray>
[np.int64(4), np.int64(7), np.int64(-5), np.int64(3)]
Length: 4, dtype: int64
RangeIndex(start=0, stop=4, step=1)

In [16]:
obj2 = pd.Series([4, 7, -5, 3], index=["d", "b", "a", "c"]) # index 지정
obj2["a"]

np.int64(-5)

In [18]:
obj2["d"] = 6 # 색인으로 접근
obj2[["a", "b", "d"]] # 색인의 배열으로 접근

a   -5
b    7
d    6
dtype: int64

In [21]:
obj2[obj2 < 0]

a   -5
dtype: int64

In [23]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [24]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [25]:
dict_data = {'A':1, 'B':2, 'C':3, 'D':4}
obj3 = pd.Series(dict_data)
obj3

A    1
B    2
C    3
D    4
dtype: int64

In [26]:
obj3.to_dict()

{'A': 1, 'B': 2, 'C': 3, 'D': 4}

In [ ]:
index = ['B', 'C', 'D', 'E']
obj4=pd.Series(dict_data, index=index) # 인덱스대로 정렬
obj4

B    2.0
C    3.0
D    4.0
E    NaN
dtype: float64

In [29]:
print(obj4.isna())
print(obj4.notna())

B    False
C    False
D    False
E     True
dtype: bool
B     True
C     True
D     True
E    False
dtype: bool

In [31]:
obj3 + obj4

A    NaN
B    4.0
C    6.0
D    8.0
E    NaN
dtype: float64

In [35]:
obj3.name = "nums" # Series 객체와 색인은 이름을 가진다.
obj3.index.name = "state"
print(obj3)

state
A    1
B    2
C    3
D    4
Name: nums, dtype: int64

In [40]:
obj.index = ["A", "B", "C", "D"] # 대입으로 인덱스를 변경할 수 있다.
obj

A    4
B    7
C   -5
D    3
dtype: int64

## 1.2. DataFrame

In [41]:
data = {"state":["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
        "year":[2001,2002,2003,2004,2005,2006],
        "pop":[1.5,1.7,3.6,2.4,2.9,3.2]}
frame = pd.DataFrame(data)
frame

    state  year  pop
0    Ohio  2001  1.5
1    Ohio  2002  1.7
2    Ohio  2003  3.6
3  Nevada  2004  2.4
4  Nevada  2005  2.9
5  Nevada  2006  3.2

In [42]:
frame.head()

    state  year  pop
0    Ohio  2001  1.5
1    Ohio  2002  1.7
2    Ohio  2003  3.6
3  Nevada  2004  2.4
4  Nevada  2005  2.9

In [44]:
pd.DataFrame(data, columns=["year","state"]) # 원하는 순서대로, 원하는 열만 지정

   year   state
0  2001    Ohio
1  2002    Ohio
2  2003    Ohio
3  2004  Nevada
4  2005  Nevada
5  2006  Nevada

In [49]:
frame2 = pd.DataFrame(data, columns=["year","state","pop","debt"]) # 딕셔너리에 없는 값은 Na
frame2

   year   state  pop debt
0  2001    Ohio  1.5  NaN
1  2002    Ohio  1.7  NaN
2  2003    Ohio  3.6  NaN
3  2004  Nevada  2.4  NaN
4  2005  Nevada  2.9  NaN
5  2006  Nevada  3.2  NaN

In [50]:
frame2["state"]

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: object

In [ ]:
frame2.loc[1]

year     2002
state    Ohio
pop       1.7
debt      NaN
Name: 1, dtype: object

In [60]:
frame2.iloc[2]

year     2003
state    Ohio
pop       3.6
debt      NaN
Name: 2, dtype: object

In [63]:
frame2["debt"] = np.arange(6.) # 대입으로 열 전체 수정
frame2

   year   state  pop  debt
0  2001    Ohio  1.5   0.0
1  2002    Ohio  1.7   1.0
2  2003    Ohio  3.6   2.0
3  2004  Nevada  2.4   3.0
4  2005  Nevada  2.9   4.0
5  2006  Nevada  3.2   5.0

In [65]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
frame2['debt'] = val # 색인에 따라 값이 대입. 존재하지 않으면 결측치가 대입된다
frame2

   year   state  pop  debt
0  2001    Ohio  1.5   NaN
1  2002    Ohio  1.7   NaN
2  2003    Ohio  3.6   NaN
3  2004  Nevada  2.4   NaN
4  2005  Nevada  2.9   NaN
5  2006  Nevada  3.2   NaN

In [67]:
frame2["isohio"] = (frame2["state"] == "Ohio") # 불리언 열 추가
frame2

   year   state  pop  debt  isohio
0  2001    Ohio  1.5   NaN    True
1  2002    Ohio  1.7   NaN    True
2  2003    Ohio  3.6   NaN    True
3  2004  Nevada  2.4   NaN   False
4  2005  Nevada  2.9   NaN   False
5  2006  Nevada  3.2   NaN   False

In [68]:
del frame2["isohio"] # 열 삭제
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [70]:
# 중첩된 딕셔너리
population = {"ohio": {2000: 1.5, 2001:1.7, 2002:3.6},
              "Nevada": {2001:2.4, 2002:2.9}}
frame3 = pd.DataFrame(population)
frame3

      ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [72]:
frame3.T

        2000  2001  2002
ohio     1.5   1.7   3.6
Nevada   NaN   2.4   2.9

In [73]:
pd.DataFrame(population, index=[2001,2002,2003])

      ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9
2003   NaN     NaN

In [75]:
frame3.index.name = "year"
frame3.columns.name = "state"
print(frame3)

state  ohio  Nevada
year
2000    1.5     NaN
2001    1.7     2.4
2002    3.6     2.9

In [76]:
frame3.to_numpy()

array([[1.5, nan],
       [1.7, 2.4],
       [3.6, 2.9]])