# 7장 데이터 정제 및 준비 실습해보기(모르는것만)

In [21]:
import pandas as pd
import numpy as np
float_data = pd.Series([1.2, -3.5, np.nan, 0])
float_data

0    1.2
1   -3.5
2    NaN
3    0.0
dtype: float64

In [22]:
data = pd.DataFrame([[1., 6.5, 3.],
                     [np.nan, np.nan, np.nan],
                     [1., np.nan, np.nan],
                     [np.nan, 6.5, 3.]])
data

     0    1    2
0  1.0  6.5  3.0
1  NaN  NaN  NaN
2  1.0  NaN  NaN
3  NaN  6.5  3.0

In [23]:
data.dropna(how='all') # 행이 모두 nan인 행만 제거

     0    1    2
0  1.0  6.5  3.0
2  1.0  NaN  NaN
3  NaN  6.5  3.0

In [25]:
data[4] = np.nan
data

     0    1    2   4
0  1.0  6.5  3.0 NaN
1  NaN  NaN  NaN NaN
2  1.0  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [26]:
data.dropna(axis='columns', how='all') # 모두 nan인 열 제거

     0    1    2
0  1.0  6.5  3.0
1  NaN  NaN  NaN
2  1.0  NaN  NaN
3  NaN  6.5  3.0

In [31]:
data = pd.DataFrame({"k1": ["one", "two"]*3 + ["two"],
                     "k2": [1,1,2,3,3,4,4]})
data

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [32]:
data.duplicated() # 각 행이 중복인지

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [34]:
data.drop_duplicates() # 6행 제거

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [36]:
data['v1'] = range(7)
data

    k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [37]:
data.drop_duplicates(subset=['k1'])

    k1  k2  v1
0  one   1   0
1  two   1   1